version: "3"
services:

  api:
    container_name: "termmerge_api"
    build:
        context: .
        dockerfile: python_docker
    command: ["/startup.sh"]
    ports: 
      - "8000:5000"
    volumes:
      - ./app:/termmerge
    links:
      - db_relational
      - db_graph
    env_file: .env
    
  db_relational:
    image: postgres:9.6.1
    container_name: "termmerge_db_relational"
    env_file: .env
    
  db_graph:
    image: neo4j:3.1.2
    container_name: "termmerge_db_graph"
    env_file: .env
    ports:
      - "7474:7474"
      - "7687:7687"
