version: "3"
services:

  api:
    image: python:3.6.0
    container_name: "termmerge_api"
    build: .
    command: "flask run --host=0.0.0.0"
    ports: 
      - "8000:5000"
    volumes:
      - "./app:/halcyon"
    links:
      - db
    env_file: .env
    
  db_relational:
    image: postgres:9.6.1
    container_name: "termmerge_db_relational"
    env_file: .env
    
  db_graph:
    image: neo4j:3.1.2
    container_name: "termmerge_db_graph"
    env_file: .env
    ports:
      - "7474:7474"
